services:
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  mailhog:
    image: arjenz/mailhog # Copy of mailhog/MailHog to support linux/arm64
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp server

  redis:
    image: redis:7.0.11
    command: "redis-server"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=devminio
      - MINIO_ROOT_PASSWORD=devminio123
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    volumes:
      - minio-data:/data

volumes:
  postgres:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local

    networks:
      - internal-formbricks-2tpvfy
    labels:
      - traefik.http.routers.internal-formbricks-2tpvfy-11-web.rule=Host(`internal-formbricks-4f55cb-159-69-14-128.traefik.me`)
      - traefik.http.routers.internal-formbricks-2tpvfy-11-web.entrypoints=web
      - traefik.http.services.internal-formbricks-2tpvfy-11-web.loadbalancer.server.port=3000
      - traefik.http.routers.internal-formbricks-2tpvfy-11-web.service=internal-formbricks-2tpvfy-11-web
      - traefik.enable=true
volumes:
  postgres-internal-formbricks-2tpvfy:
    driver: local
  uploads-internal-formbricks-2tpvfy: null
networks:
  internal-formbricks-2tpvfy:
    name: internal-formbricks-2tpvfy
    external: true
